import "../globals.css";
import { Abel, Ubuntu } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const abel = Abel({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
	variable: "--font-abel",
});

const ubuntu = Ubuntu({
	weight: ["400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-ubuntu",
});

export const metadata = {
	title: "Byte Crafters",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${ubuntu.variable} ${abel.variable}`}>
			<body>
				<Navbar />
				<div className="bg-accent1 pb-20">{children}</div>
				<Footer />
			</body>
		</html>
	);
}
